### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "username": "Mettaworldj",
  "password": "Password"
}

> {% client.global.set("auth_token", response.body.access_token); %}

### Create User
POST http://localhost:3000/auth/signup
Accept: application/json
Content-Type: application/json

{
  "email": "jon@mail.com",
  "username": "Mettaworldj",
  "profileName": "JonnyCode",
  "password": "Password"
}

### Get Current User
GET http://localhost:3000/auth/currentuser
Accept: application/json
Authorization: Bearer {{auth_token}}

### Verify User Code
POST http://localhost:3000/auth/token/verifyCode
Accept: application/json
Content-Type: application/json

{
  "code": 50071
}

> {% client.global.set("auth_token", response.body.access_token); %}
