### Create Comment
POST http://localhost:3000/comment
Accept: application/json
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "postId": 1,
  "text": "Calculus, because calculus"
}

### Get All Comments
GET http://localhost:3000/comment
Accept: application/json
Authorization: Bearer {{auth_token}}

### Delete Comment
DELETE http://localhost:3000/comment/2
Accept: application/json
Authorization: Bearer {{auth_token}}
